// <auto-generated />
using BloodBowlData.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BloodBowlMigrations.Migrations
{
    [DbContext(typeof(BloodBowlApiDbContext))]
    partial class BloodBowlAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BloodBowlData.Models.Rules.RuleSet", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Supported")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("RuleSet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Blood Bowl 2",
                            Supported = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Blood Bowl Season 2 (2020)",
                            Supported = false
                        });
                });

            modelBuilder.Entity("BloodBowlData.Models.Skills.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LocalizationDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LocalizationName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RuleSetId")
                        .HasColumnType("int");

                    b.Property<int>("SkillCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RuleSetId");

                    b.HasIndex("SkillCategoryId");

                    b.ToTable("Skill");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InternalName = "Block",
                            LocalizationDescription = "Skill.Description.BB2.Block",
                            LocalizationName = "Skill.Name.Block",
                            RuleSetId = 1,
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            InternalName = "Dauntless",
                            LocalizationDescription = "Skill.Description.BB2.Dauntless",
                            LocalizationName = "Skill.Name.Dauntless",
                            RuleSetId = 1,
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            InternalName = "DirtyPlayer",
                            LocalizationDescription = "Skill.Description.BB2.DirtyPlayer",
                            LocalizationName = "Skill.Name.DirtyPlayer",
                            RuleSetId = 1,
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            InternalName = "Fend",
                            LocalizationDescription = "Skill.Description.BB2.Fend",
                            LocalizationName = "Skill.Name.Fend",
                            RuleSetId = 1,
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            InternalName = "Frenzy",
                            LocalizationDescription = "Skill.Description.BB2.Frenzy",
                            LocalizationName = "Skill.Name.Frenzy",
                            RuleSetId = 1,
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            InternalName = "Kick",
                            LocalizationDescription = "Skill.Description.BB2.Kick",
                            LocalizationName = "Skill.Name.Kick",
                            RuleSetId = 1,
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            InternalName = "KickOffReturn",
                            LocalizationDescription = "Skill.Description.BB2.KickOffReturn",
                            LocalizationName = "Skill.Name.KickOffReturn",
                            RuleSetId = 1,
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            InternalName = "PassBlock",
                            LocalizationDescription = "Skill.Description.BB2.PassBlock",
                            LocalizationName = "Skill.Name.PassBlock",
                            RuleSetId = 1,
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            InternalName = "Pro",
                            LocalizationDescription = "Skill.Description.BB2.Pro",
                            LocalizationName = "Skill.Name.Pro",
                            RuleSetId = 1,
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 10,
                            InternalName = "Shadowing",
                            LocalizationDescription = "Skill.Description.BB2.Shadowing",
                            LocalizationName = "Skill.Name.Shadowing",
                            RuleSetId = 1,
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 11,
                            InternalName = "StripBall",
                            LocalizationDescription = "Skill.Description.BB2.StripBall",
                            LocalizationName = "Skill.Name.StripBall",
                            RuleSetId = 1,
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 12,
                            InternalName = "SureHands",
                            LocalizationDescription = "Skill.Description.BB2.SureHands",
                            LocalizationName = "Skill.Name.SureHands",
                            RuleSetId = 1,
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 13,
                            InternalName = "Tackle",
                            LocalizationDescription = "Skill.Description.BB2.Tackle",
                            LocalizationName = "Skill.Name.Tackle",
                            RuleSetId = 1,
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 14,
                            InternalName = "Wrestle",
                            LocalizationDescription = "Skill.Description.BB2.Wrestle",
                            LocalizationName = "Skill.Name.Wrestle",
                            RuleSetId = 1,
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 15,
                            InternalName = "Catch",
                            LocalizationDescription = "Skill.Description.BB2.Catch",
                            LocalizationName = "Skill.Name.Catch",
                            RuleSetId = 1,
                            SkillCategoryId = 4
                        },
                        new
                        {
                            Id = 16,
                            InternalName = "DivingCatch",
                            LocalizationDescription = "Skill.Description.BB2.DivingCatch",
                            LocalizationName = "Skill.Name.DivingCatch",
                            RuleSetId = 1,
                            SkillCategoryId = 4
                        },
                        new
                        {
                            Id = 17,
                            InternalName = "DivingTackle",
                            LocalizationDescription = "Skill.Description.BB2.DivingTackle",
                            LocalizationName = "Skill.Name.DivingTackle",
                            RuleSetId = 1,
                            SkillCategoryId = 4
                        },
                        new
                        {
                            Id = 18,
                            InternalName = "Dodge",
                            LocalizationDescription = "Skill.Description.BB2.Dodge",
                            LocalizationName = "Skill.Name.Dodge",
                            RuleSetId = 1,
                            SkillCategoryId = 4
                        },
                        new
                        {
                            Id = 19,
                            InternalName = "JumpUp",
                            LocalizationDescription = "Skill.Description.BB2.JumpUp",
                            LocalizationName = "Skill.Name.JumpUp",
                            RuleSetId = 1,
                            SkillCategoryId = 4
                        },
                        new
                        {
                            Id = 20,
                            InternalName = "Leap",
                            LocalizationDescription = "Skill.Description.BB2.Leap",
                            LocalizationName = "Skill.Name.Leap",
                            RuleSetId = 1,
                            SkillCategoryId = 4
                        },
                        new
                        {
                            Id = 21,
                            InternalName = "SideStep",
                            LocalizationDescription = "Skill.Description.BB2.SideStep",
                            LocalizationName = "Skill.Name.SideStep",
                            RuleSetId = 1,
                            SkillCategoryId = 4
                        },
                        new
                        {
                            Id = 22,
                            InternalName = "SneakyGit",
                            LocalizationDescription = "Skill.Description.BB2.SneakyGit",
                            LocalizationName = "Skill.Name.SneakyGit",
                            RuleSetId = 1,
                            SkillCategoryId = 4
                        },
                        new
                        {
                            Id = 23,
                            InternalName = "Sprint",
                            LocalizationDescription = "Skill.Description.BB2.Sprint",
                            LocalizationName = "Skill.Name.Sprint",
                            RuleSetId = 1,
                            SkillCategoryId = 4
                        },
                        new
                        {
                            Id = 24,
                            InternalName = "SureFeet",
                            LocalizationDescription = "Skill.Description.BB2.SureFeet",
                            LocalizationName = "Skill.Name.SureFeet",
                            RuleSetId = 1,
                            SkillCategoryId = 4
                        },
                        new
                        {
                            Id = 25,
                            InternalName = "Accurate",
                            LocalizationDescription = "Skill.Description.BB2.Accurate",
                            LocalizationName = "Skill.Name.Accurate",
                            RuleSetId = 1,
                            SkillCategoryId = 3
                        },
                        new
                        {
                            Id = 26,
                            InternalName = "DumpOff",
                            LocalizationDescription = "Skill.Description.BB2.DumpOff",
                            LocalizationName = "Skill.Name.DumpOff",
                            RuleSetId = 1,
                            SkillCategoryId = 3
                        },
                        new
                        {
                            Id = 27,
                            InternalName = "HailMaryPass",
                            LocalizationDescription = "Skill.Description.BB2.HailMaryPass",
                            LocalizationName = "Skill.Name.HailMaryPass",
                            RuleSetId = 1,
                            SkillCategoryId = 3
                        },
                        new
                        {
                            Id = 28,
                            InternalName = "Leader",
                            LocalizationDescription = "Skill.Description.BB2.Leader",
                            LocalizationName = "Skill.Name.Leader",
                            RuleSetId = 1,
                            SkillCategoryId = 3
                        },
                        new
                        {
                            Id = 29,
                            InternalName = "NervesOfSteel",
                            LocalizationDescription = "Skill.Description.BB2.NervesOfSteel",
                            LocalizationName = "Skill.Name.NervesOfSteel",
                            RuleSetId = 1,
                            SkillCategoryId = 3
                        },
                        new
                        {
                            Id = 30,
                            InternalName = "Pass",
                            LocalizationDescription = "Skill.Description.BB2.Pass",
                            LocalizationName = "Skill.Name.Pass",
                            RuleSetId = 1,
                            SkillCategoryId = 3
                        },
                        new
                        {
                            Id = 31,
                            InternalName = "SafeThrow",
                            LocalizationDescription = "Skill.Description.BB2.SafeThrow",
                            LocalizationName = "Skill.Name.SafeThrow",
                            RuleSetId = 1,
                            SkillCategoryId = 3
                        },
                        new
                        {
                            Id = 32,
                            InternalName = "BreakTackle",
                            LocalizationDescription = "Skill.Description.BB2.BreakTackle",
                            LocalizationName = "Skill.Name.BreakTackle",
                            RuleSetId = 1,
                            SkillCategoryId = 2
                        },
                        new
                        {
                            Id = 33,
                            InternalName = "Grab",
                            LocalizationDescription = "Skill.Description.BB2.Grab",
                            LocalizationName = "Skill.Name.Grab",
                            RuleSetId = 1,
                            SkillCategoryId = 2
                        },
                        new
                        {
                            Id = 34,
                            InternalName = "Guard",
                            LocalizationDescription = "Skill.Description.BB2.Guard",
                            LocalizationName = "Skill.Name.Guard",
                            RuleSetId = 1,
                            SkillCategoryId = 2
                        },
                        new
                        {
                            Id = 35,
                            InternalName = "Juggernaut",
                            LocalizationDescription = "Skill.Description.BB2.Juggernaut",
                            LocalizationName = "Skill.Name.Juggernaut",
                            RuleSetId = 1,
                            SkillCategoryId = 2
                        },
                        new
                        {
                            Id = 36,
                            InternalName = "MightyBlow",
                            LocalizationDescription = "Skill.Description.BB2.MightyBlow",
                            LocalizationName = "Skill.Name.MightyBlow",
                            RuleSetId = 1,
                            SkillCategoryId = 2
                        },
                        new
                        {
                            Id = 37,
                            InternalName = "MultipleBlock",
                            LocalizationDescription = "Skill.Description.BB2.MultipleBlock",
                            LocalizationName = "Skill.Name.MultipleBlock",
                            RuleSetId = 1,
                            SkillCategoryId = 2
                        },
                        new
                        {
                            Id = 38,
                            InternalName = "PilingOn",
                            LocalizationDescription = "Skill.Description.BB2.PilingOn",
                            LocalizationName = "Skill.Name.PilingOn",
                            RuleSetId = 1,
                            SkillCategoryId = 2
                        },
                        new
                        {
                            Id = 39,
                            InternalName = "StandFirm",
                            LocalizationDescription = "Skill.Description.BB2.StandFirm",
                            LocalizationName = "Skill.Name.StandFirm",
                            RuleSetId = 1,
                            SkillCategoryId = 2
                        },
                        new
                        {
                            Id = 40,
                            InternalName = "StrongArm",
                            LocalizationDescription = "Skill.Description.BB2.StrongArm",
                            LocalizationName = "Skill.Name.StrongArm",
                            RuleSetId = 1,
                            SkillCategoryId = 2
                        },
                        new
                        {
                            Id = 41,
                            InternalName = "ThickSkull",
                            LocalizationDescription = "Skill.Description.BB2.ThickSkull",
                            LocalizationName = "Skill.Name.ThickSkull",
                            RuleSetId = 1,
                            SkillCategoryId = 2
                        },
                        new
                        {
                            Id = 42,
                            InternalName = "BigHand",
                            LocalizationDescription = "Skill.Description.BB2.BigHand",
                            LocalizationName = "Skill.Name.BigHand",
                            RuleSetId = 1,
                            SkillCategoryId = 5
                        },
                        new
                        {
                            Id = 43,
                            InternalName = "Claw",
                            LocalizationDescription = "Skill.Description.BB2.Claw",
                            LocalizationName = "Skill.Name.Claw",
                            RuleSetId = 1,
                            SkillCategoryId = 5
                        },
                        new
                        {
                            Id = 44,
                            InternalName = "DisturbingPresence",
                            LocalizationDescription = "Skill.Description.BB2.DisturbingPresence",
                            LocalizationName = "Skill.Name.DisturbingPresence",
                            RuleSetId = 1,
                            SkillCategoryId = 5
                        },
                        new
                        {
                            Id = 45,
                            InternalName = "ExtraArms",
                            LocalizationDescription = "Skill.Description.BB2.ExtraArms",
                            LocalizationName = "Skill.Name.ExtraArms",
                            RuleSetId = 1,
                            SkillCategoryId = 5
                        },
                        new
                        {
                            Id = 46,
                            InternalName = "FoulAppearance",
                            LocalizationDescription = "Skill.Description.BB2.FoulAppearance",
                            LocalizationName = "Skill.Name.FoulAppearance",
                            RuleSetId = 1,
                            SkillCategoryId = 5
                        },
                        new
                        {
                            Id = 47,
                            InternalName = "Horns",
                            LocalizationDescription = "Skill.Description.BB2.Horns",
                            LocalizationName = "Skill.Name.Horns",
                            RuleSetId = 1,
                            SkillCategoryId = 5
                        },
                        new
                        {
                            Id = 48,
                            InternalName = "PrehensileTail",
                            LocalizationDescription = "Skill.Description.BB2.PrehensileTail",
                            LocalizationName = "Skill.Name.PrehensileTail",
                            RuleSetId = 1,
                            SkillCategoryId = 5
                        },
                        new
                        {
                            Id = 49,
                            InternalName = "Tentacles",
                            LocalizationDescription = "Skill.Description.BB2.Tentacles",
                            LocalizationName = "Skill.Name.Tentacles",
                            RuleSetId = 1,
                            SkillCategoryId = 5
                        },
                        new
                        {
                            Id = 50,
                            InternalName = "TwoHeads",
                            LocalizationDescription = "Skill.Description.BB2.TwoHeads",
                            LocalizationName = "Skill.Name.TwoHeads",
                            RuleSetId = 1,
                            SkillCategoryId = 5
                        },
                        new
                        {
                            Id = 51,
                            InternalName = "VeryLongLegs",
                            LocalizationDescription = "Skill.Description.BB2.VeryLongLegs",
                            LocalizationName = "Skill.Name.VeryLongLegs",
                            RuleSetId = 1,
                            SkillCategoryId = 5
                        },
                        new
                        {
                            Id = 52,
                            InternalName = "AlwaysHungry",
                            LocalizationDescription = "Skill.Description.BB2.AlwaysHungry",
                            LocalizationName = "Skill.Name.AlwaysHungry",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 53,
                            InternalName = "Animosity",
                            LocalizationDescription = "Skill.Description.BB2.Animosity",
                            LocalizationName = "Skill.Name.Animosity",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 54,
                            InternalName = "BallChain",
                            LocalizationDescription = "Skill.Description.BB2.BallChain",
                            LocalizationName = "Skill.Name.BallChain",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 55,
                            InternalName = "BloodLust",
                            LocalizationDescription = "Skill.Description.BB2.BloodLust",
                            LocalizationName = "Skill.Name.BloodLust",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 56,
                            InternalName = "Bombardier",
                            LocalizationDescription = "Skill.Description.BB2.Bombardier",
                            LocalizationName = "Skill.Name.Bombardier",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 57,
                            InternalName = "BoneHead",
                            LocalizationDescription = "Skill.Description.BB2.BoneHead",
                            LocalizationName = "Skill.Name.BoneHead",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 58,
                            InternalName = "Chainsaw",
                            LocalizationDescription = "Skill.Description.BB2.Chainsaw",
                            LocalizationName = "Skill.Name.Chainsaw",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 59,
                            InternalName = "Decay",
                            LocalizationDescription = "Skill.Description.BB2.Decay",
                            LocalizationName = "Skill.Name.Decay",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 60,
                            InternalName = "FanFavourite",
                            LocalizationDescription = "Skill.Description.BB2.FanFavourite",
                            LocalizationName = "Skill.Name.FanFavourite",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 61,
                            InternalName = "HypnoticGaze",
                            LocalizationDescription = "Skill.Description.BB2.HypnoticGaze",
                            LocalizationName = "Skill.Name.HypnoticGaze",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 62,
                            InternalName = "Loner",
                            LocalizationDescription = "Skill.Description.BB2.Loner",
                            LocalizationName = "Skill.Name.Loner",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 63,
                            InternalName = "NoHands",
                            LocalizationDescription = "Skill.Description.BB2.NoHands",
                            LocalizationName = "Skill.Name.NoHands",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 64,
                            InternalName = "NurglesRot",
                            LocalizationDescription = "Skill.Description.BB2.NurglesRot",
                            LocalizationName = "Skill.Name.NurglesRot",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 65,
                            InternalName = "ReallyStupid",
                            LocalizationDescription = "Skill.Description.BB2.ReallyStupid",
                            LocalizationName = "Skill.Name.ReallyStupid",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 66,
                            InternalName = "Regeneration",
                            LocalizationDescription = "Skill.Description.BB2.Regeneration",
                            LocalizationName = "Skill.Name.Regeneration",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 67,
                            InternalName = "RightStuff",
                            LocalizationDescription = "Skill.Description.BB2.RightStuff",
                            LocalizationName = "Skill.Name.RightStuff",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 68,
                            InternalName = "SecretWeapon",
                            LocalizationDescription = "Skill.Description.BB2.SecretWeapon",
                            LocalizationName = "Skill.Name.SecretWeapon",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 69,
                            InternalName = "Stab",
                            LocalizationDescription = "Skill.Description.BB2.Stab",
                            LocalizationName = "Skill.Name.Stab",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 70,
                            InternalName = "Stakes",
                            LocalizationDescription = "Skill.Description.BB2.Stakes",
                            LocalizationName = "Skill.Name.Stakes",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 71,
                            InternalName = "Stunty",
                            LocalizationDescription = "Skill.Description.BB2.Stunty",
                            LocalizationName = "Skill.Name.Stunty",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 72,
                            InternalName = "TakeRoot",
                            LocalizationDescription = "Skill.Description.BB2.TakeRoot",
                            LocalizationName = "Skill.Name.TakeRoot",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 73,
                            InternalName = "ThrowTeamMate",
                            LocalizationDescription = "Skill.Description.BB2.ThrowTeamMate",
                            LocalizationName = "Skill.Name.ThrowTeamMate",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 74,
                            InternalName = "Titchy",
                            LocalizationDescription = "Skill.Description.BB2.Titchy",
                            LocalizationName = "Skill.Name.Titchy",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        },
                        new
                        {
                            Id = 75,
                            InternalName = "WildAnimal",
                            LocalizationDescription = "Skill.Description.BB2.WildAnimal",
                            LocalizationName = "Skill.Name.WildAnimal",
                            RuleSetId = 1,
                            SkillCategoryId = 6
                        });
                });

            modelBuilder.Entity("BloodBowlData.Models.Skills.SkillCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("InternalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalizationShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkillCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InternalName = "General",
                            LocalizationName = "SkillCategory.Name.General",
                            LocalizationShortName = "SkillCategory.ShortName.General"
                        },
                        new
                        {
                            Id = 2,
                            InternalName = "Strength",
                            LocalizationName = "SkillCategory.Name.Strength",
                            LocalizationShortName = "SkillCategory.ShortName.Strength"
                        },
                        new
                        {
                            Id = 3,
                            InternalName = "Passing",
                            LocalizationName = "SkillCategory.Name.Passing",
                            LocalizationShortName = "SkillCategory.ShortName.Passing"
                        },
                        new
                        {
                            Id = 4,
                            InternalName = "Agility",
                            LocalizationName = "SkillCategory.Name.Agility",
                            LocalizationShortName = "SkillCategory.ShortName.Agility"
                        },
                        new
                        {
                            Id = 5,
                            InternalName = "Mutation",
                            LocalizationName = "SkillCategory.Name.Mutation",
                            LocalizationShortName = "SkillCategory.ShortName.Mutation"
                        },
                        new
                        {
                            Id = 6,
                            InternalName = "Extraordinary",
                            LocalizationName = "SkillCategory.Name.Extraordinary",
                            LocalizationShortName = "SkillCategory.ShortName.Extraordinary"
                        });
                });

            modelBuilder.Entity("BloodBowlData.Models.TeamTypes.AvailableSkillCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LevelUpTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LevelUpTypeId");

                    b.HasIndex("PlayerTypeId");

                    b.HasIndex("SkillCategoryId");

                    b.ToTable("AvailableSkillCategory");
                });

            modelBuilder.Entity("BloodBowlData.Models.TeamTypes.LevelUpType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LevelUpType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Normal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Doubles"
                        });
                });

            modelBuilder.Entity("BloodBowlData.Models.TeamTypes.PlayerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("ArmourValue")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("InternalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximumOnTeam")
                        .HasColumnType("int");

                    b.Property<int>("Move")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("TeamTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamTypeId");

                    b.ToTable("PlayerType");
                });

            modelBuilder.Entity("BloodBowlData.Models.TeamTypes.StartingSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PlayerTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerTypeId");

                    b.HasIndex("SkillId");

                    b.ToTable("StartingSkill");
                });

            modelBuilder.Entity("BloodBowlData.Models.TeamTypes.TeamType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Apothicary")
                        .HasColumnType("bit");

                    b.Property<string>("InternalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Necromancer")
                        .HasColumnType("bit");

                    b.Property<int>("RerollCost")
                        .HasColumnType("int");

                    b.Property<int>("RuleSetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RuleSetId");

                    b.ToTable("TeamType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apothicary = true,
                            InternalName = "Humans",
                            LocalizationName = "TeamType.Name.Humans",
                            Necromancer = false,
                            RerollCost = 50,
                            RuleSetId = 1
                        });
                });

            modelBuilder.Entity("BloodBowlData.Models.Skills.Skill", b =>
                {
                    b.HasOne("BloodBowlData.Models.Rules.RuleSet", "RuleSet")
                        .WithMany("Skills")
                        .HasForeignKey("RuleSetId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("BloodBowlData.Models.Skills.SkillCategory", "SkillCategory")
                        .WithMany("Skills")
                        .HasForeignKey("SkillCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuleSet");

                    b.Navigation("SkillCategory");
                });

            modelBuilder.Entity("BloodBowlData.Models.TeamTypes.AvailableSkillCategory", b =>
                {
                    b.HasOne("BloodBowlData.Models.TeamTypes.LevelUpType", "LevelUpType")
                        .WithMany("AvailableSkillCategories")
                        .HasForeignKey("LevelUpTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodBowlData.Models.TeamTypes.PlayerType", "PlayerType")
                        .WithMany("AvailableSkillCategories")
                        .HasForeignKey("PlayerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodBowlData.Models.Skills.SkillCategory", "SkillCategory")
                        .WithMany("AvailableSkillCategories")
                        .HasForeignKey("SkillCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LevelUpType");

                    b.Navigation("PlayerType");

                    b.Navigation("SkillCategory");
                });

            modelBuilder.Entity("BloodBowlData.Models.TeamTypes.PlayerType", b =>
                {
                    b.HasOne("BloodBowlData.Models.TeamTypes.TeamType", "TeamType")
                        .WithMany("PlayerTypes")
                        .HasForeignKey("TeamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamType");
                });

            modelBuilder.Entity("BloodBowlData.Models.TeamTypes.StartingSkill", b =>
                {
                    b.HasOne("BloodBowlData.Models.TeamTypes.PlayerType", "PlayerType")
                        .WithMany("StartingSkills")
                        .HasForeignKey("PlayerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodBowlData.Models.Skills.Skill", "Skill")
                        .WithMany("StartingSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerType");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("BloodBowlData.Models.TeamTypes.TeamType", b =>
                {
                    b.HasOne("BloodBowlData.Models.Rules.RuleSet", "RuleSet")
                        .WithMany("TeamTypes")
                        .HasForeignKey("RuleSetId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("RuleSet");
                });

            modelBuilder.Entity("BloodBowlData.Models.Rules.RuleSet", b =>
                {
                    b.Navigation("Skills");

                    b.Navigation("TeamTypes");
                });

            modelBuilder.Entity("BloodBowlData.Models.Skills.Skill", b =>
                {
                    b.Navigation("StartingSkills");
                });

            modelBuilder.Entity("BloodBowlData.Models.Skills.SkillCategory", b =>
                {
                    b.Navigation("AvailableSkillCategories");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("BloodBowlData.Models.TeamTypes.LevelUpType", b =>
                {
                    b.Navigation("AvailableSkillCategories");
                });

            modelBuilder.Entity("BloodBowlData.Models.TeamTypes.PlayerType", b =>
                {
                    b.Navigation("AvailableSkillCategories");

                    b.Navigation("StartingSkills");
                });

            modelBuilder.Entity("BloodBowlData.Models.TeamTypes.TeamType", b =>
                {
                    b.Navigation("PlayerTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
